owner: amblerkr
repo: status

sites:
  - name: ambler.kr
    url: https://ambler.kr/
  - name: link.ambler.kr
    url: https://link.ambler.kr/

status-website:
  theme: night
  cname: status-discord.ambler.kr
  logoUrl: https://raw.githubusercontent.com/amblerkr/amblerkr/master/img/LOGO_trans.png
  name: Ambler Status
  introTitle: "**Upptime** for Ambler"
  introMessage: Ambler Stu
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://ambler.kr/
      
